version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dapp-dynamodb
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data --cors "http://localhost:3000"
